### ISSUE TITLE
train_priv_server.py -p resnet50_classifier recv() get NoneType error

### ISSUE THREAD

**Issue by SuperBoxZero** [lightbulb128/Pencil#1]
for I am testing resnet50_classifier, in two terminals with two command:
1. python /home/bo/Pencil/pencil-prep/train_priv_server.py -p resnet50_classifier
2. python /home/bo/Pencil/pencil-prep/train_priv_client.py
but get error in the Clinet terminal
How to fix it? deal with it?
Previously I get segment fault for wrong version of cudnn with cuda, I have make that sure

Client: Model created from description successfully.
block (64, 2048, 512) -> (64, 21, 6)
block (64, 512, 2048) -> (64, 6, 21)
block (512, 64, 2048) -> (512, 1, 16)
block (512, 64, 2048) -> (4, 1, 2048)
block (64, 512, 256) -> (64, 16, 8)
block (64, 256, 512) -> (64, 8, 16)
block (256, 64, 512) -> (256, 2, 16)
block (256, 64, 512) -> (8, 2, 512)
block (64, 256, 10) -> (64, 64, 2)
block (64, 10, 256) -> (64, 2, 64)
block (10, 64, 256) -> (10, 11, 74)
block (10, 64, 256) -> (2, 16, 256)
Client: Model preprocessing finished.
Files already downloaded and verified
Files already downloaded and verified
Client: Train dataset loaded
Epoch = 0
  0%|                                                                                                                                                                                         | 0/781 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/bo/Pencil/pencil-prep/train_priv_client.py", line 105, in <module>
    output = model.forward(x)
  File "/home/bo/Pencil/pencil-prep/client_modules.py", line 1047, in forward
    x = each.forward(x)
  File "/home/bo/Pencil/pencil-prep/client_modules.py", line 210, in forward
    y = self.helper_forward.execute(x)
  File "/home/bo/Pencil/pencil-prep/client_modules.py", line 178, in execute
    k, w_masked = self.recv()
  File "/home/bo/Pencil/pencil-prep/client_modules.py", line 108, in recv
    def recv(self): return self.comm.recv()
  File "/home/bo/Pencil/pencil-prep/communication_client.py", line 48, in recv
    self.transferred += len(obj_bytes)
TypeError: object of type 'NoneType' has no len()
[MemoryPoolCuda] Released 11099552 bytes

**Comment by lightbulb128** [comment]
The NoneType error in one terminal usually means that it expects to receive a message from the other side. See if there is any error output in  the server side.
